loss: !!python/object:gluonts.torch.modules.loss.NegativeLogLikelihood
  __dict__:
    beta: 0.0
  __fields_set__: !!set {}
  __private_attribute_values__: {}
lr: 0.001
model_kwargs:
  context_length: 48
  distr_output: !!python/object:gluonts.torch.distributions.studentT.StudentTOutput
    __init_args__: !!python/object/apply:collections.OrderedDict
    - []
  hidden_dimension: 2
  kernel_size: 25
  prediction_length: 24
  scaling: std
weight_decay: 1.0e-08
